config/routes.rb
Veggie::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  #mount Resque::Server, :at => "/resque" 
  require 'sidekiq/web'
  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :members, :controllers => {
    :omniauth_callbacks => :authentications,
    :sessions => :sessions
  }
  
  namespace :mobile do
    match '/' => "mhome#index"
    match "t" => "mhome#weibo",:as => :t
    match "word" => "mhome#word"
		match "m" => "mhome#member"
  end
  
  # home
  match "welcome" => "home#index", :as => :welcome
  match "square" => "home#square", :as => :square
  
  # business
  match "b" => "business#index", :as => :business
  
  #course
  match "c" => "course#index", :as => :center
  match "c/:id" => "course#show", :as => :course
  get "course/new"
  
	# words
  namespace :words do
    get "imagine"
    post "create"
    post "u_create"
    post "add_tag"
    post "fetch_img"
  	post "upload_img_u"
  	post "upload_img_c"
    post "upload_audio_u"
  	post "annotate_u"
		post "upload_mov_u"
  	post "select_img_u"
    post "destroy_u"
  end
  
  # leafs
  match "t" => "leafs#index", :as => :leafs
  post "leafs/destroy"
  post "provider/create"
  
  # olive
  match "o" => "olive#index", :as => :olive
  namespace :olive do
    post "sync"
    post "publish"
    get "fetch"
    get "magic"
  end

  # members
  match "dashboard" => "members#dashboard",:as => :account  
  match "setting" => "members#edit",:as => :setting
  namespace :members do
    post "update"
    post "upload_avatar"
  end
  match ":role/:uid" => "members#show"
 
  root :to => 'home#door'

  # See how all your routes lay out with "rake routes"
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/views/shared/_copyright.html.haml
#footer
	%span.serif
		17up
		%span.badge.badge-success
			Alpha
		by
		= link_to "veggie",$config[:blog_host]
		Copyright © 2012-forever
	.tool
		%a(href="https://mixpanel.com/f/partner")
			%img(src="https://cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics")

app/views/shared/_flash_message.html.haml
#flash_message
	- if !flash.keys.blank?	
		- flash.keys.each do |key|
			.alert{:class => "alert-#{key}"}
				%button(type="button" class="close" data-dismiss="alert")
					%span.icon-remove-circle
				%strong= flash[key]

app/views/shared/_header.html.haml
#top_nav.navbar.navbar-fixed-top
	.navbar-inner
		.container-fluid
			%button.btn.btn-navbar(type="button" data-toggle="collapse" data-target=".nav-collapse")
				- 3.times do
					%span.icon-bar
			%span.brand.dancer
				17up
				- if @leafs and params[:pid]
					%span.tag
						&raquo;
						= Provider.find(params[:pid]).user_name
			.container.nav-collapse
				%ul.nav
					%li{:class => ("active" if @leafs)}
						= link_to leafs_path do
							%i.icon-leaf
							= t("leafs.title")
					%li{:class => ("active" if @courses)}
						= link_to center_path do
							%i.icon-book
							= t("center.title")
					%li{:class => ("active" if @users)}
						= link_to square_path do
							%i.icon-flag
							= t("square.title")
					%li{:class => ("active" if @quotes)}
						= link_to business_path do
							%i.icon-comments-alt
							= t("business.title")
				- if current_member
					%ul.nav.pull-right
						%li.member{:class => ("active" if action_name == "dashboard")}
							%a{:href => account_path}
								%i.icon-home
						%li.member{:class => ("active" if @provider_num)}
							%a{:href => setting_path }
								%i.icon-cogs
						%li
							%a(href = "/members/sign_out" data-method="delete" rel="nofollow")
								%span.label.label-important
									%i.icon-off
									登出
		

app/views/shared/_uploader.html.haml
.hidden
	= form_tag url,:remote => true,:multipart => true do
		- if defined?(wid)
			= hidden_field_tag :id,wid
		.hiddenfile
			= file_upload_for(type)