config/routes.rb
Veggie::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  #mount Resque::Server, :at => "/resque" 
  require 'sidekiq/web'
  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :members, :controllers => {
    :omniauth_callbacks => :authentications,
    :sessions => :sessions
  }
  
  namespace :mobile do
    match '/' => "mhome#index"
    match "t" => "mhome#weibo",:as => :t
    match "word" => "mhome#word"
		match "m" => "mhome#member"
  end
  
  # home
  match "welcome" => "home#index", :as => :welcome
  match "square" => "home#square", :as => :square
  
  # business
  match "b" => "business#index", :as => :business
  
  #course
  match "c" => "course#index", :as => :center
  match "c/:id" => "course#show", :as => :course
  get "course/new"
  
	# words
  namespace :words do
    get "imagine"
    post "create"
    post "u_create"
    post "add_tag"
    post "fetch_img"
  	post "upload_img_u"
  	post "upload_img_c"
    post "upload_audio_u"
  	post "annotate_u"
		post "upload_mov_u"
  	post "select_img_u"
    post "destroy_u"
  end
  
  # leafs
  match "t" => "leafs#index", :as => :leafs
  post "leafs/destroy"
  post "provider/create"
  
  # olive
  match "o" => "olive#index", :as => :olive
  namespace :olive do
    post "sync"
    post "publish"
    get "fetch"
    get "magic"
  end

  # members
  match "dashboard" => "members#dashboard",:as => :account  
  match "setting" => "members#edit",:as => :setting
  namespace :members do
    post "update"
    post "upload_avatar"
  end
  match ":role/:uid" => "members#show"
 
  root :to => 'home#door'

  # See how all your routes lay out with "rake routes"
  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/controllers/home_controller.rb
# coding: utf-8
class HomeController < ApplicationController
  caches_page :index
  
  def door
    agent = request.user_agent.downcase
    if current_member
      redirect_to account_path
    elsif agent.include?("iphone") or agent.include?("android")
      redirect_to $config[:mobile_host]
    else
      redirect_to welcome_path
    end
  end
  
  def index
    set_seo_meta(nil,t('keywords'),t('describe'))
    @is_root = true
  end
  
  def square
    set_seo_meta(t("square.title"),t('square.keywords'),t('square.describe'))
    @users = Provider.where("user_id is null")
    @fls = YAML.load_file(Rails.root.join("lib/cherry", "setting.yml")).fetch("friend_link")["course"]
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
  def contact_img_link(img_src,link,tip)
    link_to image_tag(img_src),link,:target=>"blank",:title => tip
  end

end

app/views/home/_leafs.html.haml
- @leafs.each do |leaf|
	.leaf
		- if current_member
			%span.action.destroy.hide{:onclick => "destroy_leaf(#{leaf.id},$(this));"}
				&times;
			%span.action.edit.hide
				%a{:href=>"/admin/leaf/#{leaf.id}/edit"}
					%i.icon-pencil
		.info.clearfix
			%span.avatar.left
				= my_image_tag(leaf.provider.avatar,leaf.provider.weibo)
			%span.name.left
				= link_to leaf.provider.user_name,"/p/#{leaf.provider.id}"
			%span.time.right
				= time_stamp(leaf.time_stamp)
		.content
			= auto_link(leaf.content)
		- if leaf.image
			.img
				= my_image_tag(leaf.image(:medium),leaf.image(:large))

app/views/home/_sorry.html.haml
.sorry_tip
	%h1
		%i.icon-legal
		= t('errors.browser')
	.help_link
		= link_to "http://chrome.360.cn/",:target => "blank" do
			.pic
				= image_tag('icon/chrome.png')
			.name
				360 chrome 极速浏览器

app/views/home/business.html.haml
#business
	#map-center
		%span.dancer
			love
	#quote_wrap
		- @quotes.each do |q|
			.quote_cell
				=raw q

app/views/home/index.html.haml
.logo_text
	17up
= render 'sorry'
#index_wrap
	#impress
		#register.step(data-x="0" data-y="1800" data-z="3000" data-scale="1")
			= link_to image_tag("icon/twitter_big.png"),member_omniauth_authorize_path(:twitter)		
			%span.login_tip
				登录或注册
			= link_to image_tag("icon/weibo_big.png"),member_omniauth_authorize_path(:weibo)
			%a(href="/members/sign_in")
				%span.icon-globe
		#belief.step.tallys(data-x="0" data-y="950" data-z="1500" data-scale="1")
			✿ Love can change anything
		#principle.amienne.step(data-x="0" data-y="100" data-z="0" data-scale="1")
			♛ the show must go on			
		#contact.step.text_center(data-x="0" data-y="-800" data-z="1500"  data-scale="1")
			- $contact.each do |k,v|
				= contact_img_link "icon/#{k}_big.png",v,k.to_s
			= mail_to $config[:email],image_tag("icon/gmail.png")
			%p.amienne
				contact me
		#brand.step(data-x="0" data-y="-1800" data-z="3000")
			= image_tag("/favicon.png")
			%p.dancer
				imagine

app/views/home/quote.html.haml
#quote_wrap
	- @quotes.each do |q|
		.quote_cell
			=raw q

app/views/home/square.html.haml
#square_wrap
	.banner_wrap
		%h3.banner_title.text_center.tallys
			« Links »
	#friend_link
		%ul.clearfix
			- @fls.each do |link|
				%li
					=link_to link[0].capitalize,link[1],:target => "blank"
	.banner_wrap
		%h3.banner_title.text_center.tallys
			« Gardener »
	#user_list
		- @users.each do |u|
			%a{:href => leafs_path(:pid => u.id)}
				.user_item
					.avatar
						= image_tag(u.avatar(:large))
					.name
						= image_tag("icon/#{u.provider_type}.png")
						= u.user_name

app/views/home/users.html.haml
#user_list
	- @users.each do |u|
		%a{:href => leafs_path(:pid => u.id)}
			.user_item
				.avatar
					= image_tag(u.avatar(:large))
				.name
					= image_tag("icon/#{u.provider}.png")
					= u.user_name				